--@AUTORES:									GARCIAREBOLLO
--													JUAREZ
--													SALAZAR
--@DESCRIPCION:							SCRIPT ENCARGADO DE LA CREACION DE FUNCIONES DEL PROYECTO BIBLIOTECA
--@FECHA:										16/05/19

--FUNCION ENCARGADA DEL CALCULO DE MULTAS

PROMPT CREACION DE LA FUNCION DE CALCULO DE MULTAS

CREATE OR REPLACE FUNCTION ftMulta (
	pFechaDev prestamo.fechaDevl%TYPE
	)
	RETURN NUMBER
	IS
		vMulta NUMBER(3,0):=0;
	BEGIN
		vMulta:=TRUNC(TO_NUMBER(SYSDATE-pFechaDev));
		vMulta:=vMulta*10;
		RETURN(vMulta);
END ftMulta;
/